PRODUCT_COPY_FILES += \
	vendor/vndk/vndk-26-arm64/android.frameworks.displayservice@1.0.so:system/lib64/vndk-26/android.frameworks.displayservice@1.0.so \
	vendor/vndk/vndk-26-arm64/android.frameworks.schedulerservice@1.0.so:system/lib64/vndk-26/android.frameworks.schedulerservice@1.0.so \
	vendor/vndk/vndk-26-arm64/android.frameworks.sensorservice@1.0.so:system/lib64/vndk-26/android.frameworks.sensorservice@1.0.so \
	vendor/vndk/vndk-26-arm64/android.frameworks.vr.composer@1.0.so:system/lib64/vndk-26/android.frameworks.vr.composer@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.audio@2.0.so:system/lib64/vndk-26/android.hardware.audio@2.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.audio.common@2.0.so:system/lib64/vndk-26/android.hardware.audio.common@2.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.audio.common@2.0-util.so:system/lib64/vndk-26/android.hardware.audio.common@2.0-util.so \
	vendor/vndk/vndk-26-arm64/android.hardware.audio.effect@2.0.so:system/lib64/vndk-26/android.hardware.audio.effect@2.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.automotive.evs@1.0.so:system/lib64/vndk-26/android.hardware.automotive.evs@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.automotive.vehicle@2.0.so:system/lib64/vndk-26/android.hardware.automotive.vehicle@2.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.biometrics.fingerprint@2.1.so:system/lib64/vndk-26/android.hardware.biometrics.fingerprint@2.1.so \
	vendor/vndk/vndk-26-arm64/android.hardware.bluetooth@1.0.so:system/lib64/vndk-26/android.hardware.bluetooth@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.boot@1.0.so:system/lib64/vndk-26/android.hardware.boot@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.broadcastradio@1.0.so:system/lib64/vndk-26/android.hardware.broadcastradio@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.broadcastradio@1.1.so:system/lib64/vndk-26/android.hardware.broadcastradio@1.1.so \
	vendor/vndk/vndk-26-arm64/android.hardware.camera.common@1.0.so:system/lib64/vndk-26/android.hardware.camera.common@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.camera.device@1.0.so:system/lib64/vndk-26/android.hardware.camera.device@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.camera.device@3.2.so:system/lib64/vndk-26/android.hardware.camera.device@3.2.so \
	vendor/vndk/vndk-26-arm64/android.hardware.camera.metadata@3.2.so:system/lib64/vndk-26/android.hardware.camera.metadata@3.2.so \
	vendor/vndk/vndk-26-arm64/android.hardware.camera.provider@2.4.so:system/lib64/vndk-26/android.hardware.camera.provider@2.4.so \
	vendor/vndk/vndk-26-arm64/android.hardware.configstore@1.0.so:system/lib64/vndk-26/android.hardware.configstore@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.configstore-utils.so:system/lib64/vndk-26/android.hardware.configstore-utils.so \
	vendor/vndk/vndk-26-arm64/android.hardware.contexthub@1.0.so:system/lib64/vndk-26/android.hardware.contexthub@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.drm@1.0.so:system/lib64/vndk-26/android.hardware.drm@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.dumpstate@1.0.so:system/lib64/vndk-26/android.hardware.dumpstate@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.gatekeeper@1.0.so:system/lib64/vndk-26/android.hardware.gatekeeper@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.gnss@1.0.so:system/lib64/vndk-26/android.hardware.gnss@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.graphics.allocator@2.0.so:system/lib64/vndk-26/android.hardware.graphics.allocator@2.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.graphics.bufferqueue@1.0.so:system/lib64/vndk-26/android.hardware.graphics.bufferqueue@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.graphics.composer@2.1.so:system/lib64/vndk-26/android.hardware.graphics.composer@2.1.so \
	vendor/vndk/vndk-26-arm64/android.hardware.health@1.0.so:system/lib64/vndk-26/android.hardware.health@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.ir@1.0.so:system/lib64/vndk-26/android.hardware.ir@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.keymaster@3.0.so:system/lib64/vndk-26/android.hardware.keymaster@3.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.light@2.0.so:system/lib64/vndk-26/android.hardware.light@2.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.media@1.0.so:system/lib64/vndk-26/android.hardware.media@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.media.omx@1.0.so:system/lib64/vndk-26/android.hardware.media.omx@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.memtrack@1.0.so:system/lib64/vndk-26/android.hardware.memtrack@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.nfc@1.0.so:system/lib64/vndk-26/android.hardware.nfc@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.power@1.0.so:system/lib64/vndk-26/android.hardware.power@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.radio@1.0.so:system/lib64/vndk-26/android.hardware.radio@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.radio.deprecated@1.0.so:system/lib64/vndk-26/android.hardware.radio.deprecated@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.sensors@1.0.so:system/lib64/vndk-26/android.hardware.sensors@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.soundtrigger@2.0.so:system/lib64/vndk-26/android.hardware.soundtrigger@2.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.tetheroffload.config@1.0.so:system/lib64/vndk-26/android.hardware.tetheroffload.config@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.tetheroffload.control@1.0.so:system/lib64/vndk-26/android.hardware.tetheroffload.control@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.thermal@1.0.so:system/lib64/vndk-26/android.hardware.thermal@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.tv.cec@1.0.so:system/lib64/vndk-26/android.hardware.tv.cec@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.tv.input@1.0.so:system/lib64/vndk-26/android.hardware.tv.input@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.usb@1.0.so:system/lib64/vndk-26/android.hardware.usb@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.vibrator@1.0.so:system/lib64/vndk-26/android.hardware.vibrator@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.vr@1.0.so:system/lib64/vndk-26/android.hardware.vr@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.wifi@1.0.so:system/lib64/vndk-26/android.hardware.wifi@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hardware.wifi.supplicant@1.0.so:system/lib64/vndk-26/android.hardware.wifi.supplicant@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hidl.allocator@1.0.so:system/lib64/vndk-26/android.hidl.allocator@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hidl.base@1.0.so:system/lib64/vndk-26/android.hidl.base@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hidl.token@1.0.so:system/lib64/vndk-26/android.hidl.token@1.0.so \
	vendor/vndk/vndk-26-arm64/android.hidl.token@1.0-utils.so:system/lib64/vndk-26/android.hidl.token@1.0-utils.so \
	vendor/vndk/vndk-26-arm64/android.system.net.netd@1.0.so:system/lib64/vndk-26/android.system.net.netd@1.0.so \
	vendor/vndk/vndk-26-arm64/android.system.wifi.keystore@1.0.so:system/lib64/vndk-26/android.system.wifi.keystore@1.0.so \
	vendor/vndk/vndk-26-arm64/libandroidfw.so:system/lib64/vndk-26/libandroidfw.so \
	vendor/vndk/vndk-26-arm64/libandroid_runtime.so:system/lib64/vndk-26/libandroid_runtime.so \
	vendor/vndk/vndk-26-arm64/libandroid.so:system/lib64/vndk-26/libandroid.so \
	vendor/vndk/vndk-26-arm64/libappfuse.so:system/lib64/vndk-26/libappfuse.so \
	vendor/vndk/vndk-26-arm64/libaudioclient.so:system/lib64/vndk-26/libaudioclient.so \
	vendor/vndk/vndk-26-arm64/libaudiomanager.so:system/lib64/vndk-26/libaudiomanager.so \
	vendor/vndk/vndk-26-arm64/libaudioroute.so:system/lib64/vndk-26/libaudioroute.so \
	vendor/vndk/vndk-26-arm64/libaudioutils.so:system/lib64/vndk-26/libaudioutils.so \
	vendor/vndk/vndk-26-arm64/libavservices_minijail.so:system/lib64/vndk-26/libavservices_minijail.so \
	vendor/vndk/vndk-26-arm64/libbinder.so:system/lib64/vndk-26/libbinder.so \
	vendor/vndk/vndk-26-arm64/libcamera2ndk.so:system/lib64/vndk-26/libcamera2ndk.so \
	vendor/vndk/vndk-26-arm64/libcamera_client.so:system/lib64/vndk-26/libcamera_client.so \
	vendor/vndk/vndk-26-arm64/libcamera_metadata.so:system/lib64/vndk-26/libcamera_metadata.so \
	vendor/vndk/vndk-26-arm64/libcameraservice.so:system/lib64/vndk-26/libcameraservice.so \
	vendor/vndk/vndk-26-arm64/libcap.so:system/lib64/vndk-26/libcap.so \
	vendor/vndk/vndk-26-arm64/libcrypto.so:system/lib64/vndk-26/libcrypto.so \
	vendor/vndk/vndk-26-arm64/libcrypto_utils.so:system/lib64/vndk-26/libcrypto_utils.so \
	vendor/vndk/vndk-26-arm64/libcurl.so:system/lib64/vndk-26/libcurl.so \
	vendor/vndk/vndk-26-arm64/libdebuggerd_client.so:system/lib64/vndk-26/libdebuggerd_client.so \
	vendor/vndk/vndk-26-arm64/libdiskconfig.so:system/lib64/vndk-26/libdiskconfig.so \
	vendor/vndk/vndk-26-arm64/libdng_sdk.so:system/lib64/vndk-26/libdng_sdk.so \
	vendor/vndk/vndk-26-arm64/libdrmframework.so:system/lib64/vndk-26/libdrmframework.so \
	vendor/vndk/vndk-26-arm64/libdumpstateutil.so:system/lib64/vndk-26/libdumpstateutil.so \
	vendor/vndk/vndk-26-arm64/libEGL.so:system/lib64/vndk-26/libEGL.so \
	vendor/vndk/vndk-26-arm64/libETC1.so:system/lib64/vndk-26/libETC1.so \
	vendor/vndk/vndk-26-arm64/libevent.so:system/lib64/vndk-26/libevent.so \
	vendor/vndk/vndk-26-arm64/libexif.so:system/lib64/vndk-26/libexif.so \
	vendor/vndk/vndk-26-arm64/libexpat.so:system/lib64/vndk-26/libexpat.so \
	vendor/vndk/vndk-26-arm64/libfmq.so:system/lib64/vndk-26/libfmq.so \
	vendor/vndk/vndk-26-arm64/libgatekeeper.so:system/lib64/vndk-26/libgatekeeper.so \
	vendor/vndk/vndk-26-arm64/libgui.so:system/lib64/vndk-26/libgui.so \
	vendor/vndk/vndk-26-arm64/libhardware_legacy.so:system/lib64/vndk-26/libhardware_legacy.so \
	vendor/vndk/vndk-26-arm64/libharfbuzz_ng.so:system/lib64/vndk-26/libharfbuzz_ng.so \
	vendor/vndk/vndk-26-arm64/libhwui.so:system/lib64/vndk-26/libhwui.so \
	vendor/vndk/vndk-26-arm64/libicui18n.so:system/lib64/vndk-26/libicui18n.so \
	vendor/vndk/vndk-26-arm64/libicuuc.so:system/lib64/vndk-26/libicuuc.so \
	vendor/vndk/vndk-26-arm64/libimg_utils.so:system/lib64/vndk-26/libimg_utils.so \
	vendor/vndk/vndk-26-arm64/libinput.so:system/lib64/vndk-26/libinput.so \
	vendor/vndk/vndk-26-arm64/libjavacore.so:system/lib64/vndk-26/libjavacore.so \
	vendor/vndk/vndk-26-arm64/libjnigraphics.so:system/lib64/vndk-26/libjnigraphics.so \
	vendor/vndk/vndk-26-arm64/libjpeg.so:system/lib64/vndk-26/libjpeg.so \
	vendor/vndk/vndk-26-arm64/libkeymaster1.so:system/lib64/vndk-26/libkeymaster1.so \
	vendor/vndk/vndk-26-arm64/libkeymaster_messages.so:system/lib64/vndk-26/libkeymaster_messages.so \
	vendor/vndk/vndk-26-arm64/libkeystore_binder.so:system/lib64/vndk-26/libkeystore_binder.so \
	vendor/vndk/vndk-26-arm64/libldacBT_abr.so:system/lib64/vndk-26/libldacBT_abr.so \
	vendor/vndk/vndk-26-arm64/libldacBT_enc.so:system/lib64/vndk-26/libldacBT_enc.so \
	vendor/vndk/vndk-26-arm64/liblz4.so:system/lib64/vndk-26/liblz4.so \
	vendor/vndk/vndk-26-arm64/libmediadrm.so:system/lib64/vndk-26/libmediadrm.so \
	vendor/vndk/vndk-26-arm64/libmedia_helper.so:system/lib64/vndk-26/libmedia_helper.so \
	vendor/vndk/vndk-26-arm64/libmediametrics.so:system/lib64/vndk-26/libmediametrics.so \
	vendor/vndk/vndk-26-arm64/libmedia.so:system/lib64/vndk-26/libmedia.so \
	vendor/vndk/vndk-26-arm64/libmediautils.so:system/lib64/vndk-26/libmediautils.so \
	vendor/vndk/vndk-26-arm64/libmemtrack.so:system/lib64/vndk-26/libmemtrack.so \
	vendor/vndk/vndk-26-arm64/libmemunreachable.so:system/lib64/vndk-26/libmemunreachable.so \
	vendor/vndk/vndk-26-arm64/libminijail.so:system/lib64/vndk-26/libminijail.so \
	vendor/vndk/vndk-26-arm64/libminikin.so:system/lib64/vndk-26/libminikin.so \
	vendor/vndk/vndk-26-arm64/libnativebridge.so:system/lib64/vndk-26/libnativebridge.so \
	vendor/vndk/vndk-26-arm64/libnativehelper.so:system/lib64/vndk-26/libnativehelper.so \
	vendor/vndk/vndk-26-arm64/libnativewindow.so:system/lib64/vndk-26/libnativewindow.so \
	vendor/vndk/vndk-26-arm64/libnbaio.so:system/lib64/vndk-26/libnbaio.so \
	vendor/vndk/vndk-26-arm64/libnetd_client.so:system/lib64/vndk-26/libnetd_client.so \
	vendor/vndk/vndk-26-arm64/libnetutils.so:system/lib64/vndk-26/libnetutils.so \
	vendor/vndk/vndk-26-arm64/libnl.so:system/lib64/vndk-26/libnl.so \
	vendor/vndk/vndk-26-arm64/libopus.so:system/lib64/vndk-26/libopus.so \
	vendor/vndk/vndk-26-arm64/libpackagelistparser.so:system/lib64/vndk-26/libpackagelistparser.so \
	vendor/vndk/vndk-26-arm64/libpagemap.so:system/lib64/vndk-26/libpagemap.so \
	vendor/vndk/vndk-26-arm64/libpcre2.so:system/lib64/vndk-26/libpcre2.so \
	vendor/vndk/vndk-26-arm64/libpdfium.so:system/lib64/vndk-26/libpdfium.so \
	vendor/vndk/vndk-26-arm64/libpiex.so:system/lib64/vndk-26/libpiex.so \
	vendor/vndk/vndk-26-arm64/libpng.so:system/lib64/vndk-26/libpng.so \
	vendor/vndk/vndk-26-arm64/libpowermanager.so:system/lib64/vndk-26/libpowermanager.so \
	vendor/vndk/vndk-26-arm64/libpower.so:system/lib64/vndk-26/libpower.so \
	vendor/vndk/vndk-26-arm64/libprocessgroup.so:system/lib64/vndk-26/libprocessgroup.so \
	vendor/vndk/vndk-26-arm64/libprocinfo.so:system/lib64/vndk-26/libprocinfo.so \
	vendor/vndk/vndk-26-arm64/libprotobuf-cpp-full.so:system/lib64/vndk-26/libprotobuf-cpp-full.so \
	vendor/vndk/vndk-26-arm64/libprotobuf-cpp-lite.so:system/lib64/vndk-26/libprotobuf-cpp-lite.so \
	vendor/vndk/vndk-26-arm64/libradio_metadata.so:system/lib64/vndk-26/libradio_metadata.so \
	vendor/vndk/vndk-26-arm64/libradio.so:system/lib64/vndk-26/libradio.so \
	vendor/vndk/vndk-26-arm64/librilutils.so:system/lib64/vndk-26/librilutils.so \
	vendor/vndk/vndk-26-arm64/libRScpp.so:system/lib64/vndk-26/libRScpp.so \
	vendor/vndk/vndk-26-arm64/libselinux.so:system/lib64/vndk-26/libselinux.so \
	vendor/vndk/vndk-26-arm64/libsensor.so:system/lib64/vndk-26/libsensor.so \
	vendor/vndk/vndk-26-arm64/libskia.so:system/lib64/vndk-26/libskia.so \
	vendor/vndk/vndk-26-arm64/libsoftkeymasterdevice.so:system/lib64/vndk-26/libsoftkeymasterdevice.so \
	vendor/vndk/vndk-26-arm64/libsoftkeymaster.so:system/lib64/vndk-26/libsoftkeymaster.so \
	vendor/vndk/vndk-26-arm64/libsonivox.so:system/lib64/vndk-26/libsonivox.so \
	vendor/vndk/vndk-26-arm64/libsoundtrigger.so:system/lib64/vndk-26/libsoundtrigger.so \
	vendor/vndk/vndk-26-arm64/libsparse.so:system/lib64/vndk-26/libsparse.so \
	vendor/vndk/vndk-26-arm64/libspeexresampler.so:system/lib64/vndk-26/libspeexresampler.so \
	vendor/vndk/vndk-26-arm64/libsqlite.so:system/lib64/vndk-26/libsqlite.so \
	vendor/vndk/vndk-26-arm64/libssl.so:system/lib64/vndk-26/libssl.so \
	vendor/vndk/vndk-26-arm64/libstagefright_amrnb_common.so:system/lib64/vndk-26/libstagefright_amrnb_common.so \
	vendor/vndk/vndk-26-arm64/libstagefright_enc_common.so:system/lib64/vndk-26/libstagefright_enc_common.so \
	vendor/vndk/vndk-26-arm64/libstagefright_foundation.so:system/lib64/vndk-26/libstagefright_foundation.so \
	vendor/vndk/vndk-26-arm64/libstagefright_omx.so:system/lib64/vndk-26/libstagefright_omx.so \
	vendor/vndk/vndk-26-arm64/libstagefright.so:system/lib64/vndk-26/libstagefright.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_aacdec.so:system/lib64/vndk-26/libstagefright_soft_aacdec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_aacenc.so:system/lib64/vndk-26/libstagefright_soft_aacenc.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_amrdec.so:system/lib64/vndk-26/libstagefright_soft_amrdec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_amrnbenc.so:system/lib64/vndk-26/libstagefright_soft_amrnbenc.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_amrwbenc.so:system/lib64/vndk-26/libstagefright_soft_amrwbenc.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_avcdec.so:system/lib64/vndk-26/libstagefright_soft_avcdec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_avcenc.so:system/lib64/vndk-26/libstagefright_soft_avcenc.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_flacenc.so:system/lib64/vndk-26/libstagefright_soft_flacenc.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_g711dec.so:system/lib64/vndk-26/libstagefright_soft_g711dec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_gsmdec.so:system/lib64/vndk-26/libstagefright_soft_gsmdec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_hevcdec.so:system/lib64/vndk-26/libstagefright_soft_hevcdec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_mp3dec.so:system/lib64/vndk-26/libstagefright_soft_mp3dec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_mpeg2dec.so:system/lib64/vndk-26/libstagefright_soft_mpeg2dec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_mpeg4dec.so:system/lib64/vndk-26/libstagefright_soft_mpeg4dec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_mpeg4enc.so:system/lib64/vndk-26/libstagefright_soft_mpeg4enc.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_opusdec.so:system/lib64/vndk-26/libstagefright_soft_opusdec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_rawdec.so:system/lib64/vndk-26/libstagefright_soft_rawdec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_vorbisdec.so:system/lib64/vndk-26/libstagefright_soft_vorbisdec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_vpxdec.so:system/lib64/vndk-26/libstagefright_soft_vpxdec.so \
	vendor/vndk/vndk-26-arm64/libstagefright_soft_vpxenc.so:system/lib64/vndk-26/libstagefright_soft_vpxenc.so \
	vendor/vndk/vndk-26-arm64/libstagefright_xmlparser@1.0.so:system/lib64/vndk-26/libstagefright_xmlparser@1.0.so \
	vendor/vndk/vndk-26-arm64/libstdc++.so:system/lib64/vndk-26/libstdc++.so \
	vendor/vndk/vndk-26-arm64/libsuspend.so:system/lib64/vndk-26/libsuspend.so \
	vendor/vndk/vndk-26-arm64/libsysutils.so:system/lib64/vndk-26/libsysutils.so \
	vendor/vndk/vndk-26-arm64/libtinyalsa.so:system/lib64/vndk-26/libtinyalsa.so \
	vendor/vndk/vndk-26-arm64/libtinyxml2.so:system/lib64/vndk-26/libtinyxml2.so \
	vendor/vndk/vndk-26-arm64/libui.so:system/lib64/vndk-26/libui.so \
	vendor/vndk/vndk-26-arm64/libusbhost.so:system/lib64/vndk-26/libusbhost.so \
	vendor/vndk/vndk-26-arm64/libutils.so:system/lib64/vndk-26/libutils.so \
	vendor/vndk/vndk-26-arm64/libvintf.so:system/lib64/vndk-26/libvintf.so \
	vendor/vndk/vndk-26-arm64/libvixl-arm64.so:system/lib64/vndk-26/libvixl-arm64.so \
	vendor/vndk/vndk-26-arm64/libvixl-arm.so:system/lib64/vndk-26/libvixl-arm.so \
	vendor/vndk/vndk-26-arm64/libvorbisidec.so:system/lib64/vndk-26/libvorbisidec.so \
	vendor/vndk/vndk-26-arm64/libvulkan.so:system/lib64/vndk-26/libvulkan.so \
	vendor/vndk/vndk-26-arm64/libwifi-service.so:system/lib64/vndk-26/libwifi-service.so \
	vendor/vndk/vndk-26-arm64/libwifi-system.so:system/lib64/vndk-26/libwifi-system.so \
	vendor/vndk/vndk-26-arm64/libxml2.so:system/lib64/vndk-26/libxml2.so \
	vendor/vndk/vndk-26-arm64/libyuv.so:system/lib64/vndk-26/libyuv.so \
	vendor/vndk/vndk-26-arm64/libziparchive.so:system/lib64/vndk-26/libziparchive.so \
	vendor/vndk/vndk-sp-26-arm64/android.hardware.graphics.allocator@2.0.so:system/lib64/vndk-sp-26/android.hardware.graphics.allocator@2.0.so \
	vendor/vndk/vndk-sp-26-arm64/libz.so:system/lib64/vndk-sp-26/libz.so \
	vendor/vndk/vndk-sp-26-arm64/libhardware.so:system/lib64/vndk-sp-26/libhardware.so \
	vendor/vndk/vndk-sp-26-arm64/libhidltransport.so:system/lib64/vndk-sp-26/libhidltransport.so \
	vendor/vndk/vndk-sp-26-arm64/libblas.so:system/lib64/vndk-sp-26/libblas.so \
	vendor/vndk/vndk-sp-26-arm64/android.hidl.memory@1.0.so:system/lib64/vndk-sp-26/android.hidl.memory@1.0.so \
	vendor/vndk/vndk-sp-26-arm64/libhidlbase.so:system/lib64/vndk-sp-26/libhidlbase.so \
	vendor/vndk/vndk-sp-26-arm64/hw/android.hidl.memory@1.0-impl.so:system/lib64/vndk-sp-26/hw/android.hidl.memory@1.0-impl.so \
	vendor/vndk/vndk-sp-26-arm64/android.hardware.graphics.mapper@2.0.so:system/lib64/vndk-sp-26/android.hardware.graphics.mapper@2.0.so \
	vendor/vndk/vndk-sp-26-arm64/liblzma.so:system/lib64/vndk-sp-26/liblzma.so \
	vendor/vndk/vndk-sp-26-arm64/libbcinfo.so:system/lib64/vndk-sp-26/libbcinfo.so \
	vendor/vndk/vndk-sp-26-arm64/libft2.so:system/lib64/vndk-sp-26/libft2.so \
	vendor/vndk/vndk-sp-26-arm64/libRS_internal.so:system/lib64/vndk-sp-26/libRS_internal.so \
	vendor/vndk/vndk-sp-26-arm64/android.hardware.renderscript@1.0.so:system/lib64/vndk-sp-26/android.hardware.renderscript@1.0.so \
	vendor/vndk/vndk-sp-26-arm64/libRSDriver.so:system/lib64/vndk-sp-26/libRSDriver.so \
	vendor/vndk/vndk-sp-26-arm64/libcutils.so:system/lib64/vndk-sp-26/libcutils.so \
	vendor/vndk/vndk-sp-26-arm64/android.hardware.graphics.common@1.0.so:system/lib64/vndk-sp-26/android.hardware.graphics.common@1.0.so \
	vendor/vndk/vndk-sp-26-arm64/libion.so:system/lib64/vndk-sp-26/libion.so \
	vendor/vndk/vndk-sp-26-arm64/libRSCpuRef.so:system/lib64/vndk-sp-26/libRSCpuRef.so \
	vendor/vndk/vndk-sp-26-arm64/libhwbinder.so:system/lib64/vndk-sp-26/libhwbinder.so \
	vendor/vndk/vndk-sp-26-arm64/libpng.so:system/lib64/vndk-sp-26/libpng.so \
	vendor/vndk/vndk-sp-26-arm64/libbase.so:system/lib64/vndk-sp-26/libbase.so \
	vendor/vndk/vndk-sp-26-arm64/libunwind.so:system/lib64/vndk-sp-26/libunwind.so \
	vendor/vndk/vndk-sp-26-arm64/libbacktrace.so:system/lib64/vndk-sp-26/libbacktrace.so \
	vendor/vndk/vndk-sp-26-arm64/libc++.so:system/lib64/vndk-sp-26/libc++.so \
	vendor/vndk/vndk-sp-26-arm64/android.hidl.base@1.0.so:system/lib64/vndk-sp-26/android.hidl.base@1.0.so \
	vendor/vndk/vndk-sp-26-arm64/liblog.so:system/lib64/vndk-sp-26/liblog.so \
	vendor/vndk/vndk-sp-26-arm64/libcompiler_rt.so:system/lib64/vndk-sp-26/libcompiler_rt.so \
	vendor/vndk/vndk-sp-26-arm64/libutils.so:system/lib64/vndk-sp-26/libutils.so \
	vendor/vndk/vndk-sp-26-arm64/libhidlmemory.so:system/lib64/vndk-sp-26/libhidlmemory.so \
	vendor/vndk/vndk-27-arm64/libandroidfw.so:system/lib64/vndk-27/libandroidfw.so \
	vendor/vndk/vndk-27-arm64/libandroid_runtime.so:system/lib64/vndk-27/libandroid_runtime.so \
	vendor/vndk/vndk-27-arm64/libandroid.so:system/lib64/vndk-27/libandroid.so \
	vendor/vndk/vndk-27-arm64/libappfuse.so:system/lib64/vndk-27/libappfuse.so \
	vendor/vndk/vndk-27-arm64/libaudioclient.so:system/lib64/vndk-27/libaudioclient.so \
	vendor/vndk/vndk-27-arm64/libaudiomanager.so:system/lib64/vndk-27/libaudiomanager.so \
	vendor/vndk/vndk-27-arm64/libaudiospdif.so:system/lib64/vndk-27/libaudiospdif.so \
	vendor/vndk/vndk-27-arm64/libcamera_client.so:system/lib64/vndk-27/libcamera_client.so \
	vendor/vndk/vndk-27-arm64/libdebuggerd_client.so:system/lib64/vndk-27/libdebuggerd_client.so \
	vendor/vndk/vndk-27-arm64/libdng_sdk.so:system/lib64/vndk-27/libdng_sdk.so \
	vendor/vndk/vndk-27-arm64/libdrmframework.so:system/lib64/vndk-27/libdrmframework.so \
	vendor/vndk/vndk-27-arm64/libeffectsconfig.so:system/lib64/vndk-27/libeffectsconfig.so \
	vendor/vndk/vndk-27-arm64/libEGL.so:system/lib64/vndk-27/libEGL.so \
	vendor/vndk/vndk-27-arm64/libETC1.so:system/lib64/vndk-27/libETC1.so \
	vendor/vndk/vndk-27-arm64/libGLESv2.so:system/lib64/vndk-27/libGLESv2.so \
	vendor/vndk/vndk-27-arm64/libGLESv3.so:system/lib64/vndk-27/libGLESv3.so \
	vendor/vndk/vndk-27-arm64/libharfbuzz_ng.so:system/lib64/vndk-27/libharfbuzz_ng.so \
	vendor/vndk/vndk-27-arm64/libheif.so:system/lib64/vndk-27/libheif.so \
	vendor/vndk/vndk-27-arm64/libhwui.so:system/lib64/vndk-27/libhwui.so \
	vendor/vndk/vndk-27-arm64/libicui18n.so:system/lib64/vndk-27/libicui18n.so \
	vendor/vndk/vndk-27-arm64/libicuuc.so:system/lib64/vndk-27/libicuuc.so \
	vendor/vndk/vndk-27-arm64/libimg_utils.so:system/lib64/vndk-27/libimg_utils.so \
	vendor/vndk/vndk-27-arm64/libinput.so:system/lib64/vndk-27/libinput.so \
	vendor/vndk/vndk-27-arm64/libjavacore.so:system/lib64/vndk-27/libjavacore.so \
	vendor/vndk/vndk-27-arm64/libjnigraphics.so:system/lib64/vndk-27/libjnigraphics.so \
	vendor/vndk/vndk-27-arm64/libkeystore_binder.so:system/lib64/vndk-27/libkeystore_binder.so \
	vendor/vndk/vndk-27-arm64/liblogwrap.so:system/lib64/vndk-27/liblogwrap.so \
	vendor/vndk/vndk-27-arm64/libmediadrm.so:system/lib64/vndk-27/libmediadrm.so \
	vendor/vndk/vndk-27-arm64/libmediametrics.so:system/lib64/vndk-27/libmediametrics.so \
	vendor/vndk/vndk-27-arm64/libmedia.so:system/lib64/vndk-27/libmedia.so \
	vendor/vndk/vndk-27-arm64/libmediautils.so:system/lib64/vndk-27/libmediautils.so \
	vendor/vndk/vndk-27-arm64/libmemunreachable.so:system/lib64/vndk-27/libmemunreachable.so \
	vendor/vndk/vndk-27-arm64/libminikin.so:system/lib64/vndk-27/libminikin.so \
	vendor/vndk/vndk-27-arm64/libnativebridge.so:system/lib64/vndk-27/libnativebridge.so \
	vendor/vndk/vndk-27-arm64/libnativehelper.so:system/lib64/vndk-27/libnativehelper.so \
	vendor/vndk/vndk-27-arm64/libnetd_client.so:system/lib64/vndk-27/libnetd_client.so \
	vendor/vndk/vndk-27-arm64/libpackagelistparser.so:system/lib64/vndk-27/libpackagelistparser.so \
	vendor/vndk/vndk-27-arm64/libpdfium.so:system/lib64/vndk-27/libpdfium.so \
	vendor/vndk/vndk-27-arm64/libpowermanager.so:system/lib64/vndk-27/libpowermanager.so \
	vendor/vndk/vndk-27-arm64/libprocessgroup.so:system/lib64/vndk-27/libprocessgroup.so \
	vendor/vndk/vndk-27-arm64/libRScpp.so:system/lib64/vndk-27/libRScpp.so \
	vendor/vndk/vndk-27-arm64/libselinux.so:system/lib64/vndk-27/libselinux.so \
	vendor/vndk/vndk-27-arm64/libsensorservice.so:system/lib64/vndk-27/libsensorservice.so \
	vendor/vndk/vndk-27-arm64/libsensor.so:system/lib64/vndk-27/libsensor.so \
	vendor/vndk/vndk-27-arm64/libskia.so:system/lib64/vndk-27/libskia.so \
	vendor/vndk/vndk-27-arm64/libsoftkeymaster.so:system/lib64/vndk-27/libsoftkeymaster.so \
	vendor/vndk/vndk-27-arm64/libsonivox.so:system/lib64/vndk-27/libsonivox.so \
	vendor/vndk/vndk-27-arm64/libsoundtrigger.so:system/lib64/vndk-27/libsoundtrigger.so \
	vendor/vndk/vndk-27-arm64/libsparse.so:system/lib64/vndk-27/libsparse.so \
	vendor/vndk/vndk-27-arm64/libstagefright.so:system/lib64/vndk-27/libstagefright.so \
	vendor/vndk/vndk-27-arm64/libstdc++.so:system/lib64/vndk-27/libstdc++.so \
	vendor/vndk/vndk-27-arm64/libvintf.so:system/lib64/vndk-27/libvintf.so \
	vendor/vndk/vndk-27-arm64/libvulkan.so:system/lib64/vndk-27/libvulkan.so \
	vendor/vndk/vndk-28-arm64/libbufferhubqueue.so:system/lib64/vndk-28/libbufferhubqueue.so \
	vendor/vndk/vndk-28-arm64/libeffectsconfig.so:system/lib64/vndk-28/libeffectsconfig.so \
	vendor/vndk/vndk-28-arm64/libstdc++.so:system/lib64/vndk-28/libstdc++.so \

